modLoader="javafml"

loaderVersion="[47,)"

license="All rights reserved"

[[mods]]

    modId="expansionpack"

    version="1.0.0"

    displayName="ExpansionPack"

    authors="Zhuchu"

    description='''
    整合包附带内容
    '''


[[dependencies.expansionpack]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.expansionpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"